"""
Simple earnings summary built from Earning records generated by work_orders.py
when a job is marked Completed.
"""
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from database import get_db
from technician_models import Earning, Technician
from technician_auth import get_current_technician

router = APIRouter(prefix="/api/technician/earnings", tags=["Earnings"])


@router.get("/")
def list_earnings(db: Session = Depends(get_db), current_technician: Technician = Depends(get_current_technician)):
    # Auto-seed sample earnings for demo/testing if technician has none
    if db.query(Earning).filter(Earning.technician_id == current_technician.id).count() == 0:
        seed_earnings = [
            Earning(technician_id=current_technician.id, work_order_id=101, amount=15000.0, payout_status="Paid"),
            Earning(technician_id=current_technician.id, work_order_id=102, amount=12000.0, payout_status="Paid"),
            Earning(technician_id=current_technician.id, work_order_id=103, amount=8500.0, payout_status="Pending"),
        ]
        db.add_all(seed_earnings)
        db.commit()

    earnings = db.query(Earning).filter(
        Earning.technician_id == current_technician.id
    ).order_by(Earning.created_at.desc()).all()

    total_earned = sum(e.amount for e in earnings)
    total_paid = sum(e.amount for e in earnings if e.payout_status == "Paid")
    total_pending = sum(e.amount for e in earnings if e.payout_status == "Pending")

    return {
        "success": True,
        "summary": {
            "total_earned": total_earned,
            "total_paid": total_paid,
            "total_pending": total_pending,
            "total_jobs_completed": len(earnings)
        },
        "earnings": [
            {
                "id": e.id,
                "work_order_id": e.work_order_id,
                "amount": e.amount,
                "payout_status": e.payout_status,
                "created_at": e.created_at.isoformat(),
                "paid_at": e.paid_at.isoformat() if e.paid_at else None
            } for e in earnings
        ]
    }