from fastapi import APIRouter, File, UploadFile
from google import genai
from google.genai import types
from dotenv import load_dotenv
import os, json

load_dotenv()
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
router = APIRouter()

@router.post("/api/analyze-generation")
async def analyze_generation(
    bill: UploadFile = File(...),
    generation: UploadFile = File(...)
):
    try:
        bill_data = await bill.read()
        gen_data = await generation.read()

        prompt = """
        Analyze these two images:
        1. Electricity bill image
        2. Solar inverter generation screenshot

        Extract and calculate:
        - solar_generation_units: Total units generated by solar panels
        - consumption_units: Total units consumed by user
        - export_to_grid_units: Units exported to grid (generation - consumption if positive, else 0)
        - import_from_grid_units: Units taken from grid (consumption - generation if positive, else 0)
        - net_metering_credit_rs: Export units x per unit rate
        - actual_bill_rs: Original bill amount
        - savings_rs: How much saved due to solar
        - net_payable_rs: Final amount after solar benefit

        Return ONLY valid JSON, no markdown, no explanation:
        {
            "solar_generation_units": 400,
            "consumption_units": 350,
            "export_to_grid_units": 50,
            "import_from_grid_units": 0,
            "net_metering_credit_rs": 350,
            "actual_bill_rs": 2800,
            "savings_rs": 2450,
            "net_payable_rs": 350
        }
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=[
                types.Content(role="user", parts=[
                    types.Part.from_bytes(data=bill_data, mime_type=bill.content_type),
                    types.Part.from_bytes(data=gen_data, mime_type=generation.content_type),
                    types.Part.from_text(text=prompt)
                ])
            ]
        )

        text = response.text.strip()
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0]
        elif "```" in text:
            text = text.split("```")[1].split("```")[0]

        result = json.loads(text.strip())
        return {"success": True, "data": result}

    except Exception as e:
        return {"success": False, "error": str(e)}