/**
 * Solar Production Manual Entry & Reporting Period Types
 * Phase 7A — GET Solar Energy
 *
 * Explicit distinction:
 * - Electricity Consumption = Energy drawn from or billed by utility/discom.
 * - Solar Production = Energy generated by the photovoltaic solar system.
 */

export type SolarReportingPeriodType = 'day' | 'week' | 'month' | 'year' | 'lifetime' | 'custom'

export interface DailyProductionPoint {
  id: string
  date: string
  productionKwh: number
}

export interface ManualSolarReadingPayload {
  periodType: SolarReportingPeriodType
  startDate: string
  endDate: string
  productionKwh: number
  installedCapacityKwp: number | null
  month?: string | null
  year?: string | number | null
  dailyPoints?: DailyProductionPoint[] | null
  source: 'manual'
  timestamp: string
}

export interface ManualSolarFormState {
  periodType: SolarReportingPeriodType
  date: string             // for 'day'
  weekStartDate: string    // for 'week'
  weekEndDate: string      // for 'week'
  month: string            // for 'month'
  year: string             // for 'month' and 'year'
  lifetimeAsOfDate: string // for 'lifetime'
  customStartDate: string  // for 'custom'
  customEndDate: string    // for 'custom'
  productionKwh: string
  installedCapacityKwp: string
  dailyPoints: DailyProductionPoint[]
}

export interface ManualSolarValidationErrors {
  periodType?: string
  date?: string
  startDate?: string
  endDate?: string
  productionKwh?: string
  installedCapacityKwp?: string
  dailyPoints?: string
  general?: string
}
