import type { ReportTemplate } from '../types/report.types'

export const REPORT_TEMPLATES: ReportTemplate[] = [
  {
    id: 'bill',
    title: 'Bill Analysis Report',
    description: 'Utility DISCOM tariff auditing, monthly solar sizing matching, and cost-saving projections.',
    icon: '\uD83D\uDCC4',
    category: 'assessment',
    theme: '23, 168, 229',
    displayOrder: 1,
    includes: ['Consumption Profile', 'Solar sizing', 'DISCOM breakdown'],
    supportsCSV: false,
    supportsPDF: false,
    supportsPreview: false,
    estimatedGenerationTime: '~30 seconds',
    emptyStateMessage: 'Upload a bill to generate this report.',
    requiredPermissions: [],
    generateConfig: { endpoint: null, method: 'POST' },
    previewConfig: { endpoint: null },
    downloadConfig: { endpoint: null },
  },
  {
    id: 'roof',
    title: 'Roof Assessment Report',
    description: 'Panel placement optimisation, shading analysis, structural suitability scoring.',
    icon: '\uD83C\uDFE0',
    category: 'technical',
    theme: '54, 211, 153',
    displayOrder: 2,
    includes: ['Panel placement', 'Shading analysis', 'Suitability score'],
    supportsCSV: false,
    supportsPDF: false,
    supportsPreview: false,
    estimatedGenerationTime: '~45 seconds',
    emptyStateMessage: 'Complete a roof scan to generate this report.',
    requiredPermissions: [],
    generateConfig: { endpoint: null, method: 'POST' },
    previewConfig: { endpoint: null },
    downloadConfig: { endpoint: null },
  },
  {
    id: 'roi',
    title: 'ROI & Financial Report',
    description: 'Break-even charting, net cost analysis, 25-year lifetime ROI projections.',
    icon: '\uD83D\uDCCA',
    category: 'financial',
    theme: '255, 138, 29',
    displayOrder: 3,
    includes: ['Break-even chart', 'Net cost', 'Lifetime ROI'],
    supportsCSV: false,
    supportsPDF: false,
    supportsPreview: false,
    estimatedGenerationTime: '~20 seconds',
    emptyStateMessage: 'Run an ROI calculation to generate this report.',
    requiredPermissions: [],
    generateConfig: { endpoint: '/api/calculate-roi', method: 'POST' },
    previewConfig: { endpoint: null },
    downloadConfig: { endpoint: null },
  },
  {
    id: 'comprehensive',
    title: 'Comprehensive Report',
    description: 'Full solar intelligence dossier: cover page, readiness score, next-steps checklist.',
    icon: '\uD83D\uDCC4',
    category: 'comprehensive',
    theme: '234, 179, 8',
    displayOrder: 4,
    includes: ['Cover page', 'Readiness score', 'Next steps checklist'],
    supportsCSV: false,
    supportsPDF: false,
    supportsPreview: false,
    estimatedGenerationTime: '~60 seconds',
    emptyStateMessage: 'Complete all assessments to generate a comprehensive report.',
    requiredPermissions: [],
    generateConfig: { endpoint: null, method: 'POST' },
    previewConfig: { endpoint: null },
    downloadConfig: { endpoint: null },
  },
]
