import type {
  CanonicalCertification,
  CertificationsDashboardData,
  AdaptedCertificationsData,
} from '../types/certifications.types'
import { EXPIRATION_THRESHOLD_DAYS } from '../constants/certifications.constants'

export function adaptCertificationsData(dashboard: CertificationsDashboardData): AdaptedCertificationsData {
  const raw = dashboard.certifications || []
  const now = new Date()

  // Calculate dynamic status and derived collections
  const processed = raw.map((cert) => {
    const validTillDate = new Date(cert.validTill)
    const diffMs = validTillDate.getTime() - now.getTime()
    const diffDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24))

    let status = cert.status
    if (diffDays < 0) {
      status = 'Expired'
    } else if (diffDays <= EXPIRATION_THRESHOLD_DAYS) {
      status = 'Expiring'
    }

    return {
      ...cert,
      status,
    }
  })

  const active = processed.filter(c => c.status === 'Active' || c.status === 'Expiring')
  const completed = processed.filter(c => c.status !== 'Pending')
  const expiring = processed.filter(c => c.status === 'Expiring')

  // Timeline dynamically generated by sorting canonical records by issuedAt DESC
  const timeline = [...completed].sort((a, b) =>
    new Date(b.issuedAt).getTime() - new Date(a.issuedAt).getTime()
  )

  return {
    raw: processed,
    all: processed,
    active,
    completed,
    expiring,
    timeline,
    summary: {
      totalActive: active.length,
      totalCompleted: completed.length,
      totalExpiring: expiring.length,
      skillLevel: dashboard.summary.skillLevel,
      overallScorePercent: dashboard.summary.overallScorePercent,
    },
    badges: dashboard.badges || [],
    skills: dashboard.skills || [],
    recommendations: dashboard.recommendations || [],
  }
}
