import type {
  BillAnalysisData,
  SolarReportData,
  UnifiedEnergyData,
} from '../hooks/billAnalyzer.types'

export interface MetricExplanation {
  metricKey: string
  label: string
  whatItMeans: string
  whyYouSeeThis: string
  decisionImpact: string
}

export const DEMO_EXPLANATIONS: Record<string, MetricExplanation> = {
  gridImport: {
    metricKey: 'gridImport',
    label: 'Grid Import',
    whatItMeans:
      'Total units of electricity drawn from your distribution utility (Discom) grid during periods when household electricity demand exceeded real-time solar production.',
    whyYouSeeThis:
      'Extracted directly from your bidirectional electricity meter reading recorded on your monthly utility bill.',
    decisionImpact:
      'High grid import during daylight hours indicates an opportunity to shift high-load appliances (such as ACs or pumps) into peak solar production windows.',
  },
  gridExport: {
    metricKey: 'gridExport',
    label: 'Grid Export',
    whatItMeans:
      'Surplus solar energy generated by your rooftop PV system that was not consumed on-site and was exported back into the Discom power grid.',
    whyYouSeeThis:
      'Recorded by your export register on the net meter and credited against your total grid consumption under your state net-metering regulations.',
    decisionImpact:
      'Quantifies your exported units to determine whether your export tariff credit offsets fixed charges or rolls forward into future billing cycles.',
  },
  solarGeneration: {
    metricKey: 'solarGeneration',
    label: 'Solar Generation',
    whatItMeans:
      'The aggregate volume of clean electricity produced by your rooftop solar PV modules and inverter over the monthly billing cycle.',
    whyYouSeeThis:
      'Extracted from your inverter monitoring application report (e.g. SolarEdge, Growatt) or calculated from your plant capacity.',
    decisionImpact:
      'Demonstrates your true primary renewable power output before electrical distribution into home appliances or the power grid.',
  },
  solarSelfConsumption: {
    metricKey: 'solarSelfConsumption',
    label: 'Solar Self-Consumption',
    whatItMeans:
      'Solar electricity used directly within your premises the instant it is generated, powering household lights, refrigerators, appliances, and HVAC.',
    whyYouSeeThis:
      'Derived mathematically by subtracting metered grid export from total inverter solar generation (Solar Generation − Grid Export).',
    decisionImpact:
      'Self-consumed units deliver the maximum financial value by avoiding high peak-slab retail tariffs without relying on export credit rates.',
  },
  selfConsumptionRate: {
    metricKey: 'selfConsumptionRate',
    label: 'Self-Consumption Rate',
    whatItMeans:
      'The proportion of total solar energy produced that was used directly inside the home rather than pushed to the grid.',
    whyYouSeeThis:
      'Calculated as (Direct Solar Self-Consumption ÷ Total Solar Generation) × 100.',
    decisionImpact:
      'Rates between 60% and 75% are typical for residential systems. Higher rates shorten payback duration and maximize direct bill offset.',
  },
  exportRate: {
    metricKey: 'exportRate',
    label: 'Solar Export Rate',
    whatItMeans:
      'The percentage of monthly solar electricity exported to the grid when household power demand was lower than plant output.',
    whyYouSeeThis:
      'Calculated as (Metered Grid Export ÷ Total Solar Generation) × 100.',
    decisionImpact:
      'Helps evaluate whether battery storage or automated daytime scheduling could convert exported units into direct household savings.',
  },
  netGridEnergy: {
    metricKey: 'netGridEnergy',
    label: 'Net Grid Energy',
    whatItMeans:
      'The physical net energy exchange across the meter connection (Grid Import units minus Grid Export units).',
    whyYouSeeThis:
      'Physical meter computation: Grid Import (380.0 kWh) − Grid Export (145.0 kWh) = 235.0 kWh.',
    decisionImpact:
      'Represents your true physical balance with the grid, distinct from financial billing slabs and tariff surcharges.',
  },
  netBilledUnits: {
    metricKey: 'netBilledUnits',
    label: 'Net Billed Units',
    whatItMeans:
      'The actual energy units subject to tariff charges on your utility bill after adjusting physical net grid energy against accumulated solar surplus credits.',
    whyYouSeeThis:
      'Calculated on your utility invoice: Net Grid Energy (235.0 kWh) minus Opening Solar Surplus (120.0 kWh) = 115.0 kWh invoiced.',
    decisionImpact:
      'This is the authoritative volume of units applied to your Discom tariff slab to compute your current electricity charge.',
  },
  openingSurplus: {
    metricKey: 'openingSurplus',
    label: 'Opening Surplus',
    whatItMeans:
      'Cumulative unused solar generation credits carried forward into this billing cycle from previous months of excess export.',
    whyYouSeeThis:
      'Extracted directly from the Discom net-metering energy ledger table on your electricity invoice.',
    decisionImpact:
      'Proves your previous seasonal credits are honored by the utility, providing a buffer against higher consumption during peak summer cycles.',
  },
  closingSurplus: {
    metricKey: 'closingSurplus',
    label: 'Closing Surplus',
    whatItMeans:
      'The remaining bank of solar energy credits available to roll over into the subsequent month after covering this cycle’s net grid demand.',
    whyYouSeeThis:
      'Calculated by the Discom ledger: max(0, Opening Surplus − Net Grid Energy). At 0 kWh, all banked credits were utilized this cycle.',
    decisionImpact:
      'Monitors your annual solar banking balance before the state utility annual settlement and true-up period.',
  },
  specificYield: {
    metricKey: 'specificYield',
    label: 'Specific Yield',
    whatItMeans:
      'Normalized electrical output generated per kilowatt of installed solar capacity over the monthly cycle (kWh per kWp).',
    whyYouSeeThis:
      'Calculated as Total Generation (412.5 kWh) divided by System Capacity (3.0 kW) = 137.5 kWh/kWp.',
    decisionImpact:
      'Benchmarks equipment health independent of plant size. A specific yield between 120 and 145 kWh/kWp indicates excellent operational efficiency.',
  },
  performancePct: {
    metricKey: 'performancePct',
    label: 'Performance %',
    whatItMeans:
      'Comparison of actual real-world generation against standard engineering benchmark expectations for your climate zone.',
    whyYouSeeThis:
      'Computed as (Actual Generation ÷ Expected Generation) × 100. For 412.5 kWh actual vs 375.0 kWh expected, performance is 110.0%.',
    decisionImpact:
      'Confirms whether panels require maintenance (dust/soiling cleaning) or if inverter parameters are operating at peak efficiency.',
  },
  expectedGeneration: {
    metricKey: 'expectedGeneration',
    label: 'Expected Generation',
    whatItMeans:
      'The baseline monthly solar energy an optimal residential installation of this capacity is engineered to produce.',
    whyYouSeeThis:
      'Calculated using standard engineering yield benchmark: System Capacity (3.0 kW) × 125 kWh/kW = 375 kWh/month.',
    decisionImpact:
      'Establishes the performance baseline against which actual inverter readings and warranties are measured.',
  },
  billAmount: {
    metricKey: 'billAmount',
    label: 'Bill Amount',
    whatItMeans:
      'Total charges payable to your power utility for the billing period, combining net energy units, fixed charges, fuel adjustments, and taxes.',
    whyYouSeeThis:
      'Extracted from the final payable total on your electricity bill invoice.',
    decisionImpact:
      'Establishes your baseline recurring energy expenditure to determine solar sizing and payback period.',
  },
  potentialSavings: {
    metricKey: 'potentialSavings',
    label: 'Potential Savings',
    whatItMeans:
      'Projected reduction in monthly utility expenditure achieved through combined direct solar consumption and net-metering export credits.',
    whyYouSeeThis:
      'Calculated based on estimated generation (375 kWh) multiplied by your average effective tariff rate (₹9.08/kWh).',
    decisionImpact:
      'Demonstrates your recurring financial dividend, generating an estimated ~82% reduction in recurring grid electricity costs.',
  },
}

export const DEMO_BILL_ANALYZER_DATA: {
  analysis: BillAnalysisData
  solarReport: SolarReportData
  unifiedEnergy: UnifiedEnergyData
} = {
  analysis: {
    customer_name: 'Sample Homeowner',
    consumer_number: '1009823471',
    discom: 'BSES Rajdhani Power Ltd',
    billing_period: 'June 2026',
    monthly_units: 380,
    bill_amount: 3450,
    per_unit_rate: 9.08,
    recommended_kw: 3.0,
    monthly_generation_units: 375,
    monthly_savings_rs: 2835,
    system_cost_rs: 165000,
    payback_years: 2.6,
    savings_25_years_rs: 763500,

    solarYield: 125,
    monthlySolarGeneration: 375,
    annualSolarGeneration: 4500,
    solarUsedDirectly: 267.5,
    solarExportedToGrid: 145.0,
    solarOffsetPercent: 98.7,
    gridDependency: 112.5,
    netMeteringBenefit: 1015,

    isSolarConsumer: true,
    importUnits: 380.0,
    exportUnits: 145.0,
    solarGeneratedUnits: 412.5,
    netConsumptionUnits: 235.0,
    netConsumption: 235.0,
    netMeteringCredit: 1015,

    openingSolarSurplus: 120.0,
    closingSolarSurplus: 0.0,
    netBilledUnits: 115.0,
    gridImport: 380.0,
    gridExport: 145.0,

    extractionConfidence: {
      score: 98,
      label: 'High Confidence',
      badgeClass: 'confidence-high',
    },
    billHealth: {
      score: 92,
      rating: 'Optimal',
    },
    solarOpportunity: {
      score: 95,
      rating: 'Prime Opportunity',
    },
    filename: 'sample_delhi_residential_bill.pdf',
  },

  solarReport: {
    productionKwh: 412.5,
    systemSizeKw: 3.0,
    month: 'June',
    year: 2026,
    source: 'SolarEdge App',
    dailyGenerationKwh: 13.75,
    confidence: '98%',
  },

  unifiedEnergy: {
    solarGenerated: 412.5,
    gridImport: 380.0,
    gridExport: 145.0,
    solarUsedDirectly: 267.5,
    selfConsumptionPct: 64.8,
    solarOffsetPct: 108.6,
    gridDependencyPct: 35.2,
    netMeteringBenefit: 1015,
  },
}
