export const JOURNEY_CONFIG = {
  "ST-01": {
    id: "ST-01",
    slug: "estimate",
    displayName: "Estimate Created",
    description: "Your initial solar potential sizing estimate has been configured.",
    owner: "system",
    etaDays: 1,
    unlockRoutes: ["/app/home", "/app/journey"],
    requiredDocs: [],
    customerAction: "REVIEW_ESTIMATE",
    completionRules: "Has valid estimated system size.",
    progressWeight: 5
  },
  "ST-02": {
    id: "ST-02",
    slug: "bill-uploaded",
    displayName: "Utility Bill Uploaded",
    description: "Please upload your recent electricity bill to verify consumption details.",
    owner: "customer",
    etaDays: 1,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills"],
    requiredDocs: ["UTILITY_BILL"],
    customerAction: "UPLOAD_BILL",
    completionRules: "file_path is not null",
    progressWeight: 10
  },
  "ST-03": {
    id: "ST-03",
    slug: "bill-verified",
    displayName: "Bill Data Verified",
    description: "Engineering team is verifying your DISCOM tariff parameters.",
    owner: "admin",
    etaDays: 2,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills"],
    requiredDocs: [],
    customerAction: "WAIT_FOR_VERIFICATION",
    completionRules: "admin_approved_at is not null",
    progressWeight: 20
  },
  "ST-04": {
    id: "ST-04",
    slug: "roof-assessed",
    displayName: "Roof Assessment Complete",
    description: "Satellite analytics have mapped your roof orientation and suitability.",
    owner: "system",
    etaDays: 1,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof"],
    requiredDocs: [],
    customerAction: "APPROVE_ROOF_LAYOUT",
    completionRules: "layout_approved_at is not null",
    progressWeight: 30
  },
  "ST-05": {
    id: "ST-05",
    slug: "proposal-ready",
    displayName: "Engineering Proposal Ready",
    description: "Your investor-grade solar sizing proposal is ready for review.",
    owner: "system",
    etaDays: 1,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal"],
    requiredDocs: ["PROPOSAL_DOCUMENT"],
    customerAction: "ACCEPT_PROPOSAL",
    completionRules: "contract_signed_at is not null",
    progressWeight: 40
  },
  "ST-06": {
    id: "ST-06",
    slug: "customer-approval",
    displayName: "Proposal Approved",
    description: "You have approved the solar proposal. A site survey is being scheduled.",
    owner: "customer",
    etaDays: 1,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal"],
    requiredDocs: ["SIGNED_AGREEMENT"],
    customerAction: "SCHEDULE_SURVEY",
    completionRules: "survey_scheduled_at is not null",
    progressWeight: 50
  },
  "ST-07": {
    id: "ST-07",
    slug: "site-survey",
    displayName: "Site Survey Complete",
    description: "A certified surveyor will verify structural integrity and roof metrics.",
    owner: "engineer",
    etaDays: 3,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal"],
    requiredDocs: ["SITE_SURVEY_REPORT"],
    customerAction: "WAIT_FOR_SURVEY",
    completionRules: "survey_report_uploaded is not null",
    progressWeight: 60
  },
  "ST-08": {
    id: "ST-08",
    slug: "installation-scheduled",
    displayName: "Installation Scheduled",
    description: "Our certified EPC installation team is preparing hardware mounting.",
    owner: "vendor",
    etaDays: 5,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal", "/app/installation/progress"],
    requiredDocs: [],
    customerAction: "PREPARE_SITE",
    completionRules: "installation_complete_at is not null",
    progressWeight: 70
  },
  "ST-09": {
    id: "ST-09",
    slug: "installation-complete",
    displayName: "Installation Complete",
    description: "Physical panels and inverter mount completed. Quality check pending.",
    owner: "vendor",
    etaDays: 1,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal", "/app/installation/progress"],
    requiredDocs: ["COMMISSIONING_CERTIFICATE"],
    customerAction: "WAIT_FOR_INSPECTION",
    completionRules: "qa_inspected_at is not null",
    progressWeight: 80
  },
  "ST-10": {
    id: "ST-10",
    slug: "quality-inspection",
    displayName: "QA Inspection Verified",
    description: "Certified GET Solar engineer has checked wiring, grounding, and output.",
    owner: "engineer",
    etaDays: 2,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal", "/app/installation/progress", "/app/installation/qa"],
    requiredDocs: ["VERIFICATION_CERTIFICATE"],
    customerAction: "APPLY_NET_METERING",
    completionRules: "net_meter_installed_at is not null",
    progressWeight: 85
  },
  "ST-11": {
    id: "ST-11",
    slug: "net-metering",
    displayName: "Net Metering Active",
    description: "DISCOM is installing net metering equipment to sync with the grid.",
    owner: "vendor",
    etaDays: 7,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal", "/app/installation/progress", "/app/installation/qa", "/app/installation/net-metering"],
    requiredDocs: ["NOC_DISCOM"],
    customerAction: "WAIT_FOR_GRID_SYNC",
    completionRules: "grid_active_at is not null",
    progressWeight: 90
  },
  "ST-12": {
    id: "ST-12",
    slug: "monitoring-active",
    displayName: "System Active & Monitoring",
    description: "Congratulations! Your solar system is fully active, generating power, and offsetting grid consumption.",
    owner: "system",
    etaDays: 0,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal", "/app/installation/progress", "/app/installation/qa", "/app/installation/net-metering", "/app/ownership/system", "/app/ownership/savings", "/app/ownership/reports", "/app/ownership/documents"],
    requiredDocs: ["WARRANTY_DOCUMENTS"],
    customerAction: "NONE",
    completionRules: "active",
    progressWeight: 100
  },
  "ST-13": {
    id: "ST-13",
    slug: "maintenance",
    displayName: "Maintenance & AMC",
    description: "System is covered under standard active annual maintenance agreements.",
    owner: "vendor",
    etaDays: 365,
    unlockRoutes: ["/app/home", "/app/journey", "/app/planning/bills", "/app/planning/roof", "/app/planning/proposal", "/app/installation/progress", "/app/installation/qa", "/app/installation/net-metering", "/app/ownership/system", "/app/ownership/savings", "/app/ownership/reports", "/app/ownership/documents"],
    requiredDocs: ["AMC_AGREEMENT"],
    customerAction: "NONE",
    completionRules: "active",
    progressWeight: 100
  }
};
